KayaBiya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('dashboard.urls')),
    path('', include('member.urls')),
    path('', include('deposit.urls')),
    path('', include('loan.urls')),
    path('', include('report.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loan/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('loan-list/', views.LoanListView.as_view(), name='loan_list'),
    path('loan-request/', views.LoanRequestView.as_view(), name='loan_request'),
    path('loan-disbursed/', views.LoanDisbursedView.as_view(), name='loan_disbursed'),
    path('loan-settled/', views.LoanSettledView.as_view(), name='loan_settled'),
    path('loan-voided/', views.LoanVoidedView.as_view(), name='loan_voided'),
    path('loan-watchlist/', views.LoanWatchlistView.as_view(), name='loan_watchlist'),

    path('loan-apply/', views.LoanApplyView.as_view(), name='loan_apply'),
    path('loan-update/<str:pk>/', views.LoanUpdateView.as_view(), name='loan_update'),
    
    path('loan-account-create/', views.LoanAccountCreateView.as_view(), name='loan_account_create'),
    path('loan-account-list/', views.LoanAccountListView.as_view(), name='loan_account_list'),

    path('loan-interest-list/<str:pk>/', views.LoanInterestListView.as_view(), name='loan_interest_list'),
    path('loan-interest-update/<str:pk>/', views.LoanInterestUpdateView.as_view(), name='loan_interest_update')


    # path('loan-repay/', views.LoanRepaymentView.as_view(), name='loan_repay'),
   
]

deposit/models.py
from datetime import datetime
from django.db import models

from member.models import Member

# Create your models here.
class Deposit(models.Model):
    date = models.DateField(default=datetime.now)
    account = models.ForeignKey(Member, on_delete=models.CASCADE)
    deposit_amount = models.PositiveIntegerField()
    deposit_by = models.CharField(max_length=50, default="Self")
    remarks = models.CharField(max_length=100, blank=True, null=True)

member/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils import timezone

    
    

class Community(models.Model):
    community_name = models.CharField(max_length=255)
    community_head = models.ManyToManyField(User, related_name='managed_community')

    def __str__(self):
        return self.community_name
    


class Member(models.Model):
    MARITAL_STATUS = [
        ('Single', 'Single'),
        ('Married', 'Married'),
    ]
    GENDER = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
    STATUS = [
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    ]
    MEMBER_TYPE = [
        ('General', 'General'),
        ('Executive', 'Executive'),
    ]
    ROLE_CHOICES = [
        ('Member', 'Member'),
        ('Community-Head', 'Community-Head'),
        ('Executive', 'Executive'),
    ]
    
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='Member')
    community = models.ForeignKey(Community, on_delete=models.CASCADE, blank=True, null=True, related_name='community_members')
    membership_id = models.CharField(max_length=20, blank=True, null=True)
    grand_parent = models.CharField(max_length=20, blank=True, null=True)
    parent = models.CharField(max_length=20, blank=True, null=True)
    spouse = models.CharField(max_length=20, blank=True, null=True)
    
    gender = models.CharField(max_length=6, choices=GENDER, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    marital_status = models.CharField(
        max_length=7, choices=MARITAL_STATUS, null=True, blank=True
    )
    mobile = models.CharField(max_length=10, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    ward = models.CharField(max_length=3, null=True, blank=True)
    house_number = models.CharField(max_length=10, blank=True)
    citizenship_number = models.CharField(max_length=10, blank=True)
    join_date = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to="profile/", blank=True, null=True)
    citizen_copy = models.ImageField(upload_to="citizen/", blank=True, null=True)
    status = models.CharField(max_length=8, choices=STATUS, default="Active")
    # Auto Generated Fields
    age = models.IntegerField(null=True, blank=True)
    member_id = models.CharField(max_length=6, unique=True, blank=True)

    def save(self, *args, **kwargs):
        # Calculation of Age
        if self.dob:
            current_date = timezone.now().date()
            self.age = current_date.year - self.dob.year
        else:
            pass

        # Member ID Generation
        if not self.member_id:
            last_member = Member.objects.all().order_by('id').last()
            if last_member:
                last_member_id = int(last_member.member_id)
                self.member_id = f'{last_member_id + 1:03d}'
            else:
                self.member_id = "001"

        super().save(*args, **kwargs)

    
    def __str__(self):
        return str(self.username.get_full_name())
    

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>KayaBiya</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport" />
    <link rel="icon" href="{% static 'assets/img/24px.png' %}" type="image/x-icon" />

    <!-- Fonts and icons -->
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugins.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/kaiadmin.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}" />
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <div class="wrapper">
      <!-- Nav Sidebar -->
      {% include 'base/navbar_side.html' %}
      <!-- End Nav Sidebar -->

      <div class="main-panel">
        <!-- Nav Topbar -->
        {% include 'base/navbar_top.html' %}
        <!-- End Nav Topbar -->

        <div class="container">
          <div class="page-inner">
            {% block content %}

            {% endblock %}
          </div>
        </div>

        <!-- Footer -->
        {% include 'base/footer.html' %}
        <!-- End Footer -->
      </div>
    </div>

    <!-- Core JS Files -->
    <script src="{% static 'assets/js/core/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>

    <!-- jQuery Scrollbar -->
    <script src="{% static 'assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

    <!-- Chart JS -->
    <script src="{% static 'assets/js/plugin/chart.js/chart.min.js' %}"></script>

    <!-- jQuery Sparkline -->
    <script src="{% static 'assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

    <!-- Chart Circle -->
    <script src="{% static 'assets/js/plugin/chart-circle/circles.min.js' %}"></script>

    <!-- Datatables -->
    <script src="{% static 'assets/js/plugin/datatables/datatables.min.js' %}"></script>

    <!-- Bootstrap Notify -->
    <script src="{% static 'assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

    <!-- jQuery Vector Maps -->
    <script src="{% static 'assets/js/plugin/jsvectormap/jsvectormap.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jsvectormap/world.js' %}"></script>

    <!-- Sweet Alert -->
    <script src="{% static 'assets/js/plugin/sweetalert/sweetalert.min.js' %}"></script>

    <!-- Kaiadmin JS -->
    <script src="{% static 'assets/js/kaiadmin.min.js' %}"></script>
    <!-- Extra JS -->
    <script src="{% static 'assets/js/extra.js' %}"></script>

    <!-- htmx JS -->
    <script src="{% static 'assets/js/htmx.min.js' %}"></script>


    {% block extrajs %}

    {% endblock %}

    
  </body>
</html>

templates/base/error_messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <span style="margin-right: 15px;">{{ message }} </span>
    </div>
  {% endfor %}
{% endif %}

templates/base/footer.html
{% load static %}
{% comment %} <footer class="footer">
  <div class="container-fluid d-flex justify-content-between">
    <nav class="pull-left">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="http://www.themekita.com">ThemeKita</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Help</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Licenses</a>
        </li>
      </ul>
    </nav>
    <div class="copyright">
      2024, made with <i class="fa fa-heart heart text-danger"></i> by
      <a href="http://www.themekita.com">ThemeKita</a>
    </div>
    <div>
      Distributed by
      <a target="_blank" href="https://themewagon.com/">ThemeWagon</a>.
    </div>
  </div>
</footer> {% endcomment %}


<footer class="footer">
  <div class="d-flex justify-content-between container-fluid">
    <span class="text-white">Copyright © Perfect Solution 2024</span>
    <div class="text-center">
        <img src="{% static 'assets/img/logo2cm.png' %}" alt="" style="height: 60px;">
    </div>
    <span class="text-right text-white">
        For <a href="https://www.lakasanepal.org/" target="_blank">Lakasa Nepal</a> from Perfect Solution
    </span>
  </div>
</footer>

templates/base/navbar_side.html
{% load static %}
<div class="sidebar" data-background-color="dark">
  <div class="sidebar-logo">
    <!-- Logo Header -->
    <div class="logo-header" data-background-color="dark">
      <a href="" class="logo"><img src="{% static 'assets/img/logo5cm.png' %}" alt="navbar brand" class="navbar-brand" height="60" /> <span style="color: antiquewhite; margin-left: 10px; font-weight: bolder;">KAYA BIYA</span></a>
      <div class="nav-toggle">
        <button class="btn btn-toggle toggle-sidebar"><i class="gg-menu-right"></i></button>
        <button class="btn btn-toggle sidenav-toggler"><i class="gg-menu-left"></i></button>
      </div>
      <button class="topbar-toggler more"><i class="gg-more-vertical-alt"></i></button>
    </div>
    <!-- End Logo Header -->
  </div>
  <div class="sidebar-wrapper scrollbar scrollbar-inner">
    <div class="sidebar-content">
      <ul class="nav nav-secondary">
        <li class="nav-item">
          <a href="{% url 'dashboard' %}" class="collapsed">
            <i class="fas fa-home"></i>
            <p>Dashboard</p>
          </a>
        </li>
        {% if user.is_staff or user.managed_community.exists %}
          <li class="nav-item">
            <a href="{% url 'community_list' %}">
              <i class="fas fa-layer-group"></i>
              <p>Community</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account' %}">
              <i class="fas fa-layer-group"></i>
              <p>Accounts</p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'member_list' %}">
              <i class="fas fa-layer-group"></i>
              <p>Members</p>
            </a>
          </li>

          <li class="nav-item">
            <a data-bs-toggle="collapse" href="#sidebarDeposit">
              <i class="fas fa-th-list"></i>
              <p>Deposit</p>
              <span class="caret"></span>
            </a>
            <div class="collapse" id="sidebarDeposit">
              <ul class="nav nav-collapse">
                <li>
                  <a href="{% url 'deposit_list' %}"><span class="sub-item">View All</span></a>
                </li>
                <li>
                  <a href="{% url 'deposit_create' %}"><span class="sub-item">Single Entry</span></a>
                </li>
                <li>
                  <a href="{% url 'multideposit_create' %}"><span class="sub-item">Multiple Entry</span></a>
                </li>
              </ul>
            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'deposit_list' %}">
              <i class="fas fa-th-list"></i>
              <p>My Deposits</p>
            </a>
          </li>
        {% endif %}

        <li class="nav-item">
          <a data-bs-toggle="collapse" href="#sidebarLoanStatus">
            <i class="fas fa-th-list"></i>
            <p>Loan Status</p>
            <span class="caret"></span>
          </a>
          <div class="collapse" id="sidebarLoanStatus">
            <ul class="nav nav-collapse">
              <li>
                <a href="{% url 'loan_request' %}"><span class="sub-item">Request</span></a>
              </li>
              <li>
                <a href="{% url 'loan_disbursed' %}"><span class="sub-item">Disbursed</span></a>
              </li>
              <li>
                <a href="{% url 'loan_settled' %}"><span class="sub-item">Settled</span></a>
              </li>
              {% if user.is_staff or user.managed_community.exists %}
              <li>
                <a href="{% url 'loan_voided' %}"><span class="sub-item">Voided</span></a>
              </li>
              <li>
                <a href="{% url 'loan_watchlist' %}"><span class="sub-item">WatchList/Flagged</span></a>
              </li>
              {% endif %}
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a data-bs-toggle="collapse" href="#sidebarLoanRepayment">
            <i class="fas fa-th-list"></i>
            <p>Loan Repayment</p>
            <span class="caret"></span>
          </a>
          <div class="collapse" id="sidebarLoanRepayment">
            <ul class="nav nav-collapse">
              <li>
                <a href="{% url 'loan_account_list' %}"><span class="sub-item">Loaner List</span></a>
              </li>
            </ul>
          </div>
        </li>

        {% comment %} <li class="nav-item">
          <a href="{% url 'loan_list' %}">
            <i class="fas fa-layer-group"></i>
            <p>Loan</p>
          </a>
        </li> {% endcomment %}
        <li class="nav-item">
          <a href="">
            <i class="fas fa-layer-group"></i>
            <p>Reports</p>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

templates/base/navbar_top.html
{% load static %}
<div class="main-header">
  <div class="main-header-logo">
    <!-- Logo Header For Small Screen Size -->
    <div class="logo-header" data-background-color="dark">
      <a href="" class="logo"><img src="" alt="navbar brand" class="navbar-brand" height="20" /></a>
      <div class="nav-toggle">
        <button class="btn btn-toggle toggle-sidebar"><i class="gg-menu-right"></i></button>
        <button class="btn btn-toggle sidenav-toggler"><i class="gg-menu-left"></i></button>
      </div>
      <button class="topbar-toggler more"><i class="gg-more-vertical-alt"></i></button>
    </div>
    <!-- End Logo Header -->
  </div>
  <!-- Navbar Header -->
  <nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
    <div class="container-fluid">
      <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex"></nav>

      <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
        <li class="nav-item topbar-icon dropdown hidden-caret">
          <a class="nav-link dropdown-toggle" href="#" id="messageDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-envelope"></i></a>
          <ul class="dropdown-menu messages-notif-box animated fadeIn" aria-labelledby="messageDropdown">
            <li>
              <div class="dropdown-title d-flex justify-content-between align-items-center">
                Messages
                <a href="#" class="small">Mark all as read</a>
              </div>
            </li>
            <li>
              <div class="message-notif-scroll scrollbar-outer">
                <div class="notif-center">
                  <a href="#">
                    <div class="notif-img">
                      <img src="{% static 'assets/img/jm_denis.jpg' %}" alt="Img Profile" />
                    </div>
                    <div class="notif-content">
                      <span class="subject">Jimmy Denis</span>
                      <span class="block">How are you ?</span>
                      <span class="time">5 minutes ago</span>
                    </div>
                  </a>

                  <a href="#">
                    <div class="notif-img">
                      <img src="{% static 'assets/img/talha.jpg' %}" alt="Img Profile" />
                    </div>
                    <div class="notif-content">
                      <span class="subject">Talha</span>
                      <span class="block">Hi, Apa Kabar ?</span>
                      <span class="time">17 minutes ago</span>
                    </div>
                  </a>
                </div>
              </div>
            </li>
            <li>
              <a class="see-all" href="javascript:void(0);">See all messages<i class="fa fa-angle-right"></i></a>
            </li>
          </ul>
        </li>
        <li class="nav-item topbar-icon dropdown hidden-caret">
          <a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-bell"></i>
            <span class="notification">4</span>
          </a>
          <ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
            <li>
              <div class="dropdown-title">You have 4 new notification</div>
            </li>
            <li>
              <div class="notif-scroll scrollbar-outer">
                <div class="notif-center">
                  <a href="#">
                    <div class="notif-icon notif-primary">
                      <i class="fa fa-user-plus"></i>
                    </div>
                    <div class="notif-content">
                      <span class="block">New user registered</span>
                      <span class="time">5 minutes ago</span>
                    </div>
                  </a>

                  <a href="#">
                    <div class="notif-icon notif-danger">
                      <i class="fa fa-heart"></i>
                    </div>
                    <div class="notif-content">
                      <span class="block">Farrah liked Admin</span>
                      <span class="time">17 minutes ago</span>
                    </div>
                  </a>
                </div>
              </div>
            </li>
            <li>
              <a class="see-all" href="javascript:void(0);">See all notifications<i class="fa fa-angle-right"></i></a>
            </li>
          </ul>
        </li>
        <li class="nav-item topbar-icon dropdown hidden-caret">
          <a class="nav-link" data-bs-toggle="dropdown" href="#" aria-expanded="false"><i class="fas fa-layer-group"></i></a>
          <div class="dropdown-menu quick-actions animated fadeIn">
            <div class="quick-actions-header">
              <span class="title mb-1">Quick Actions</span>
              <span class="subtitle op-7">Shortcuts</span>
            </div>
            <div class="quick-actions-scroll scrollbar-outer">
              <div class="quick-actions-items">
                <div class="row m-0">
                  <a class="col-6 col-md-4 p-0" href="#">
                    <div class="quick-actions-item">
                      <div class="avatar-item bg-danger rounded-circle">
                        <i class="far fa-calendar-alt"></i>
                      </div>
                      <span class="text">Calendar</span>
                    </div>
                  </a>
                  <a class="col-6 col-md-4 p-0" href="#">
                    <div class="quick-actions-item">
                      <div class="avatar-item bg-warning rounded-circle">
                        <i class="fas fa-map"></i>
                      </div>
                      <span class="text">Maps</span>
                    </div>
                  </a>
                  <a class="col-6 col-md-4 p-0" href="#">
                    <div class="quick-actions-item">
                      <div class="avatar-item bg-info rounded-circle">
                        <i class="fas fa-file-excel"></i>
                      </div>
                      <span class="text">Reports</span>
                    </div>
                  </a>
                  <a class="col-6 col-md-4 p-0" href="#">
                    <div class="quick-actions-item">
                      <div class="avatar-item bg-success rounded-circle">
                        <i class="fas fa-envelope"></i>
                      </div>
                      <span class="text">Emails</span>
                    </div>
                  </a>
                  <a class="col-6 col-md-4 p-0" href="#">
                    <div class="quick-actions-item">
                      <div class="avatar-item bg-primary rounded-circle">
                        <i class="fas fa-file-invoice-dollar"></i>
                      </div>
                      <span class="text">Invoice</span>
                    </div>
                  </a>
                  <a class="col-6 col-md-4 p-0" href="#">
                    <div class="quick-actions-item">
                      <div class="avatar-item bg-secondary rounded-circle">
                        <i class="fas fa-credit-card"></i>
                      </div>
                      <span class="text">Payments</span>
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </li>

        <li class="nav-item topbar-user dropdown hidden-caret">
          <a class="dropdown-toggle profile-pic" data-bs-toggle="dropdown" href="#" aria-expanded="false">
            <div class="avatar-sm">
              {% if user.member.profile_picture %}
              <img src="{{ user.member.profile_picture.url }}" alt="PP" class="avatar-img rounded-circle" />
              {% elif user.member.gender == "Male" %}
              <img src="{% static 'assets/image/profile_male.jpg' %}" alt="PP" class="avatar-img rounded-circle" />
              {% else %}
              <img src="{% static 'assets/image/profile_female.png' %}" alt="PP" class="avatar-img rounded-circle" />
              {% endif %}
            </div>
            <span class="profile-username">
              <span class="op-7">Hi,</span>
              <span class="fw-bold">{{user.get_full_name|title}}</span>
            </span>
          </a>
          <ul class="dropdown-menu dropdown-user animated fadeIn">
            <div class="dropdown-user-scroll scrollbar-outer">
              
              <li>
                
                <a class="dropdown-item" href="#">My Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
              </li>
            </div>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
  <!-- End Navbar -->
</div>